### ISSUE TITLE
Dudes I got my main discord account banned

### ISSUE THREAD

**Issue by encloinc** [ScReGr/calicode-www#6]
I got my main discord account banned, can you guys give me an invite link to the calicode server pls

**Comment by versocre** [comment]
herronjo's account got disabled too. 

https://discord.gg/zjJSBT

**Comment by RecyclingBiin** [comment]
Same here... I need an invite too

**Comment by encloinc** [comment]
> Same here... I need an invite too

https://discord.gg/w64fGa
